In [30]:
import numpy as np

In [31]:
def back_substitution(A, b):
    # L is a lower triangular matrix and b is a vector.
    n = len(b)
    x = np.zeros(n)
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - A[i, i + 1:n] @ x[i + 1:n]) / A[i, i]
    return x

In [32]:
def forward_elimination(A, b):
    n = len(b)
    for k in range(n - 1):
        for i in range(k + 1, n):
            c = A[i][k] / A[k][k]
            A[i][k:n] = A[i][k:n] - c * A[k][k:n]
            b[i] = b[i] - c * b[k]
    return [A, b]

In [33]:
def pivot_forward_elimination(A, b):
    n = len(A)
    for k in range(n - 1):
        i_max = np.argmax(np.abs(A[k:n, k])) + k
        if i_max != k:
            A[[k, i_max], :] = A[[i_max, k], :]
            b[[k, i_max]] = b[[i_max, k]]
        for i in range(k + 1, n):
            c = A[i][k] / A[k][k]
            A[i][k:n] = A[i][k:n] - c * A[k][k:n]
            b[i] = b[i] - c * b[k]

In [34]:
def gaussian_elimination(A, b):
    """Function that returns the matrix U and vector c after the gaussian elimination

    Parameters:
        A (np.array): A matrix
        b (np.array): The vector b

    returns:
        U (np.array): The matrix U after the gaussian elimination
        c (np.array): The vector c after the gaussian elimination
    """
    forward_elimination(A, b)
    return back_substitution(A, b)

In [39]:
def pivot_gaussian_elimination(A, b):
    """Function that returns the matrix U and vector c after the pivot gaussian elimination

    Parameters:
        A (np.array): A matrix
        b (np.array): The vector b

    returns:
        U (np.array): The matrix U after the gaussian elimination
        c (np.array): The vector c after the gaussian elimination
    """
    pivot_forward_elimination(A, b)
    return back_substitution(A, b)

In [36]:
# Check the function
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]], dtype=float)
b = np.array([1, 1, 1], dtype=float)

A0 = np.copy(A)
b0 = np.copy(b)

x = gaussian_elimination(A0, b0)
print(f"The matrix A after gaussian elimination is:\n{A0}")
print(f"The vector b after gaussian elimination is: {b0}")
print(f"The result is {x}")

The matrix A after gaussian elimination is:
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  1.]]
The vector b after gaussian elimination is: [ 1. -3.  0.]
The result is [-1.  1.  0.]


In [37]:
# Ex 1
A = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 10]], dtype=float)
b = np.array([1, 1, 1], dtype=float)

A0 = np.copy(A)
b0 = np.copy(b)

x = pivot_gaussian_elimination(A0, b0)
print(f"The matrix A after gaussian elimination is:\n{A0}")
print(f"The vector b after gaussian elimination is: {b0}")
print(f"The result is {x}")

The matrix A after gaussian elimination is:
[[ 7.          8.         10.        ]
 [ 0.          2.          3.        ]
 [ 0.          0.         -0.35714286]]
The vector b after gaussian elimination is: [1.         1.         0.21428571]
The result is [-0.6  1.4 -0.6]


In [38]:
# Ex 2
# Ex 1
A = np.array([[1, 2, 3], [2, 4, 7], [8, 9, 11]], dtype=float)
b = np.array([1, 1, 1], dtype=float)

A0 = np.copy(A)
b0 = np.copy(b)

x = pivot_gaussian_elimination(A0, b0)
print(f"The matrix A after gaussian elimination is:\n{A0}")
print(f"The vector b after gaussian elimination is: {b0}")
print(f"The result is {x}")

The matrix A after gaussian elimination is:
[[ 8.    9.   11.  ]
 [ 0.    1.75  4.25]
 [ 0.    0.   -0.5 ]]
The vector b after gaussian elimination is: [1.   0.75 0.5 ]
The result is [-1.71428571  2.85714286 -1.        ]


In [42]:
# Ex 3
# Method to compute the determinant of the matrix

def det(mat, n):
    # Base case: if the matrix is 1x1
    if n == 1:
        return mat[0][0]

    # Base case for 2x2 matrix
    if n == 2:
        return mat[0][0] * mat[1][1] - \
            mat[0][1] * mat[1][0]

    # Recursive case for larger matrices
    res = 0
    for col in range(n):

        # Create a submatrix by removing the first
        # row and the current column
        sub = [[0] * (n - 1) for _ in range(n - 1)]
        for i in range(1, n):
            subcol = 0
            for j in range(n):

                # Skip the current column
                if j == col:
                    continue

                # Fill the submatrix
                sub[i - 1][subcol] = mat[i][j]
                subcol += 1

        # Cofactor expansion
        sign = 1 if col % 2 == 0 else -1
        res += sign * mat[0][col] * det(sub, n - 1)

    return res


A = np.array([[1, 2, 3], [2, 4, 7], [8, 9, 11]], dtype=float)
print(det(A, len(A)))

7.0
